services:
  http1:
    image: nginx:alpine
    volumes:
      - ./http1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./shared:/usr/share/nginx/html:ro
    ports:
      - "8081:80"

  http2:
    build:
      context: ./http2
    volumes:
      - ./shared:/usr/share/caddy/html:ro
    ports:
      - "8082:443"
    expose:
      - "443"
#
#  http3:
#    image: nginx:mainline-alpine
#    volumes:
#      - ./http3/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./shared:/usr/share/nginx/html:ro
#    ports:
#      - "8083:443/udp"
#      - "8083:443/tcp"
#
